### ISSUE TITLE
Unable to visualize media fields 

### ISSUE THREAD

**Issue by DamperDoor56** [mattmilburn/strapi-plugin-menus#87]
## Hi !
Hi! First of all, I really admire all the work you've done with this plugin, It's just what I needed for my project, so thank you very much for doing this! 🥇 

## Troubles
Back to the issue, I created a custom media field, along others and when I click on the media one, it crashes.
The others work perfectly fine.
![strapi](https://res.cloudinary.com/dweiaqd6l/image/upload/v1675451363/strapi_v9ci1t.png)
![strapierror](https://res.cloudinary.com/dweiaqd6l/image/upload/v1675451468/console_error_uq1lvi.png)

I don't know if I'm missing something or if this is a bug, anyway thank you again for your time and for doing this amazing plugin! :)

## Files

- Console errors:

```
TypeError: Cannot read properties of null (reading 'allowedTypes')

TypeError: Cannot read properties of null (reading 'allowedTypes')

```

- `extensions/menus/strapi-server.js`
```
'use strict';

module.exports = plugin => {
  // Get current `MenuItem` attributes.
  const defaultAttrs = plugin.contentTypes[ 'menu-item' ].schema.attributes;

  // Define custom attributes for `MenuItem` the same way they would be defined
  // on any other schema.
  const customAttrs = {
    example_bool: {
      type: 'boolean',
    },
    example_text: {
      type: 'string',
    },
    example_email: {
      type: 'email',
    },
    example_password: {
      type: 'password',
    },
    example_richtext: {
      type: 'richtext',
    },
    example_date: {
      type: 'date',
    },
    example_time: {
      type: 'time',
    },
    example_datetime: {
      type: 'datetime',
    },
    example_integer: {
      type: 'integer',
    },
    example_biginteger: {
      type: 'biginteger',
    },
    example_decimal: {
      type: 'decimal',
    },
    example_float: {
      type: 'float',
    },
    example_enum: {
      type: 'enumeration',
      enum: [
        'option1',
        'option2',
        'option3',
      ],
    },
    example_media: {
      type: 'media',
      allowedTypes: [ 'images' ],
      multiple: false,
    },
    example_relation_one: {
      type: 'relation',
      relation: 'oneToOne',
      target: 'api::example-one.example-one',
    },
    example_relation_many: {
      type: 'relation',
      relation: 'oneToMany',
      target: 'api::example-many.example-many',
    },
  };

  // Extend the `MenuItem` content type with custom attributes.
  plugin.contentTypes[ 'menu-item' ].schema.attributes = {
    ...defaultAttrs,
    ...customAttrs,
  };

  return plugin;
};
```

- `./config/plugins.ts`
```
export default {
    menus: {
      config: {
        maxDepth: 3,
        layouts: {
          menuItem: {
            link: [
              {
                input: {
                  label: 'Boolean',
                  name: 'example_bool',
                  type: 'bool',
                },
                grid: {
                  col: 6,
                },
              },
            ],
            text: [
              {
                input: {
                  label: 'Text',
                  name: 'example_text',
                  type: 'text',
                },
              },
              {
                input: {
                  label: 'Email',
                  name: 'example_email',
                  type: 'email',
                },
              },
              {
                input: {
                  label: 'Password',
                  name: 'example_password',
                  type: 'password',
                },
              },
              {
                input: {
                  label: 'Rich Text',
                  name: 'example_richtext',
                  type: 'wysiwyg',
                  description: 'This field type is not supported unless a custom plugin overrides the core WYSIWYG editor.',
                },
              },
            ],
            date: [
              {
                input: {
                  label: 'Date',
                  name: 'example_date',
                  type: 'date',
                },
                grid: {
                  col: 6,
                },
              },
              {
                input: {
                  label: 'Time',
                  name: 'example_time',
                  type: 'time',
                },
                grid: {
                  col: 6,
                },
              },
              {
                input: {
                  label: 'Date and Time',
                  name: 'example_datetime',
                  type: 'datetime',
                },
              },
            ],
            number: [
              {
                input: {
                  label: 'Integer',
                  name: 'example_integer',
                  type: 'number',
                },
                grid: {
                  col: 6,
                },
              },
              {
                input: {
                  label: 'Big Integer',
                  name: 'example_biginteger',
                  type: 'number',
                },
                grid: {
                  col: 6,
                },
              },
              {
                input: {
                  label: 'Decimal',
                  name: 'example_decimal',
                  type: 'number',
                },
                grid: {
                  col: 6,
                },
              },
              {
                input: {
                  label: 'Float',
                  name: 'example_float',
                  type: 'number',
                },
                grid: {
                  col: 6,
                },
              },
            ],
            media: [
              {
                input: {
                  label: 'Media',
                  name: 'example_media',
                  type: 'media',
                },
                grid: {
                  col: 6,
                },
              },
            ],
            select: [
              {
                input: {
                  label: 'Enumeration',
                  name: 'example_enum',
                  type: 'select',
                  options: [
                    {
                      label: 'Option Label 1',
                      value: 'option1',
                    },
                    {
                      label: 'Option Label 2',
                      value: 'option2',
                    },
                    {
                      label: 'Option Label 3',
                      value: 'option3',
                    },
                  ],
                },
              },
              {
                input: {
                  label: 'Relation (hasOne)',
                  name: 'example_relation_one',
                  type: 'relation',
                },
              },
              {
                input: {
                  label: 'Relation (hasMany)',
                  name: 'example_relation_many',
                  type: 'relation',
                },
              },
            ],
          },
        },
      },
    },
  };
```

- `package.json`
```
{
  "name": "cms",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "@strapi/plugin-i18n": "4.6.0",
    "@strapi/plugin-users-permissions": "4.6.0",
    "@strapi/strapi": "4.6.0",
    "mysql": "2.18.1",
    "strapi-plugin-menus": "^1.3.0"
  },
  "author": {
    "name": "Ludmi"
  },
  "strapi": {
    "uuid": "e8faa4b1-ca2d-4f98-ae2a-3cb2c429657c"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

```

**Comment by DamperDoor56** [comment]
Nevermind! I fixed it! For someone who is having the same issue this is what i did:

- (I made this project in ts) I changed `extensions/menus/strapi-server.js` to `extensions/menus/strapi-server.ts` and instead of putting 
```
module.exports = plugin => {
...
}
```
I put 
```
export default(plugin) => {
...}
```

Sorry to bother! I hope It helps someone

**Comment by lechinoix** [comment]
Hello ! I think this is not solved actually, I am experiencing the same issue. It seems to be related to the fact that `allowedTypes` are not getting to the attribute field correctly, and that [the default value](https://github.com/strapi/strapi/commit/c3fd52c24a938477dcdc90614b7790b90def7733#diff-e1735634e1aa9e8592c3302b2f1be9a4c1cf045d5753c406584abb6d43a2a369R462) is now null so overriding the default values of `MediaLibraryInput`

**Comment by lechinoix** [comment]
@mattmilburn Might be worth reopening it, I have also raised an issue on Strapi

**Comment by lechinoix** [comment]
Actually I rebased on latest version and it works like a charm 👌

**Comment by joelveloso** [comment]
Running last version still a problem to me:


config/plugins.js

 ```
 menus: {
    config: {
      maxDepth: 3,
      layouts: {
        menuItem: {
          media: [
            {
              input: {
                label: "Media",
                name: "media",
                type: "media",
                allowedTypes: ["images"],
                multiple: false,
              },
              grid: {
                col: 6,
              },
            },
          ],
        },
      },
    },
  },
```

"strapi-plugin-menus": "1.6.0",
"@strapi/strapi": "4.15.5",

**Comment by jakubjenis** [comment]
Was hitting this error for strapi 4.16.2, when following the docs and adding a media type field, but workaround mentioned by @DamperDoor56 works
