### ISSUE TITLE
Add media attributes  to the MenuItem will get error and break strapi

### ISSUE THREAD

**Issue by jonsnowljs** [mattmilburn/strapi-plugin-menus#96]
## Environment

- Strapi: 4.8.0,
- strapi-plugin-menus: 1.3.2

## What i have done

- Created plugin config at ` config/plugins.ts`

```js
export default ({ env }) => ({
          media: [
            {
              input: {
                label: 'Media',
                name: 'example_media',
                type: 'media'
              }
            }
          ],
})

```

- Created attributes extension at `src/extensions/strapi-server.js`
```js
module.exports = (plugin) => {
  // Get current `MenuItem` attributes.
  const defaultAttrs = plugin.contentTypes['menu-item'].schema.attributes

  const customAttrs = {
    example_media: {
      allowedTypes: ['images'],
      type: 'media',
      multiple: false
    },
}

```

## Error message I got

Hi, thank you for your great plugin. I have tried all the other extension attributes configs you provided in the document, and they all work. The only one not working is the media. When I click the tab it will always break the strapi and I get the following  error message

``` 
TypeError: Cannot read properties of null (reading 'allowedTypes')
```

**Comment by mattmilburn** [comment]
Hi @jonsnowljs I was able to reproduce this issue and the way I fixed it was running `yarn build` locally and then running `yarn develop` again.

I don't believe this happens when running `yarn develop --watch-admin` but I'm beginning to test Strapi both ways now.

Let me know if this helps.

**Comment by haidertm** [comment]
Ran yarn build. Still the page breaks. 

![image](https://github.com/mattmilburn/strapi-plugin-menus/assets/95686585/bb780ebe-9a79-4550-904c-83361db24144)

**Comment by joelveloso** [comment]
Same happening to me. Breaks the page, exact same 2 errors. build does not fix it.
